### PR TITLE
Feature/flow tests

### PR DESCRIPTION
**Pull request by basdijkstra**
This PR adds flow tests to the repository.

When integrating these in CI, they can be run using `dotnet test --filter FlowTests`

### CODE REVIEW

**Comment by basdijkstra** [comment]
The only way I could get these tests to work (for now) is by adding a short sleep before clicking the 'Login' button. The problem is that even though the button is visible and enabled, it takes a while in Firefox before it is *actually* clickable. There's probably a more elegant solution, but for now this will have to do.

**Comment by basdijkstra** [comment]
@mstrelex did you have the time to look into this already? See email from @vitalybu from January 20 about potentially starting a new session before the Agent can accept them.. I'd like to see these tests added to the CI.

**Comment by vitalybu** [comment]
@basdijkstra, I rebased this branch and now it fails on a totally different issue

**Comment by basdijkstra** [comment]
> @basdijkstra, I rebased this branch and now it fails on a totally different issue

I see, let's see if I can reproduce this locally and try and find a fix.

**Pull request merged**
